"""
portfolio_visual.py
-------------------
Portfolio structure visualization from the snapshot CSV.

Reads:   ../data/portfolio.csv      (generated by call_api.py)
Writes:  ../Results/portfolio_visual.png

Three panels:
  1. Donut   — allocation by asset type
  2. H-bars  — top-15 positions by value (excl. cash)
  3. Stacked — breakdown by brokerage account

Usage:
    /opt/miniconda3/bin/python portfolio_visual.py
"""

import pathlib
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd
from matplotlib.gridspec import GridSpec

_ROOT    = pathlib.Path(__file__).parent.parent
SNAPSHOT = _ROOT / "data" / "portfolio.csv"
RESULTS  = _ROOT / "Results"
OUT_PATH = RESULTS / "portfolio_visual.png"

# ── Bloomberg-style dark palette ───────────────────────────────────────────────

_DARK_BG  = "#0D1117"
_PANEL_BG = "#161B22"
_TEXT     = "#E6EDF3"
_DIM      = "#8B949E"
_GRID     = "#21262D"

TYPE_PALETTE = {
    "share":          "#58A6FF",
    "bond":           "#3FB950",
    "etf":            "#D29922",
    "precious_metal": "#F0C040",
    "currency":       "#6E7681",
    "crypto":         "#F78166",
}
TYPE_LABELS = {
    "share":          "Акции",
    "bond":           "Облигации",
    "etf":            "Фонды",
    "precious_metal": "Драг. металлы",
    "currency":       "Деньги",
    "crypto":         "Крипта",
}


def _dark_theme() -> None:
    plt.rcParams.update({
        "figure.facecolor": _DARK_BG,  "axes.facecolor":  _PANEL_BG,
        "axes.edgecolor":   _GRID,     "axes.labelcolor":  _DIM,
        "axes.titlecolor":  _TEXT,     "xtick.color":      _DIM,
        "ytick.color":      _DIM,      "grid.color":       _GRID,
        "grid.linewidth":   0.6,       "text.color":       _TEXT,
        "legend.facecolor": _PANEL_BG, "legend.edgecolor": _GRID,
        "legend.labelcolor":_TEXT,     "font.family":      "DejaVu Sans",
    })


def load_snapshot() -> pd.DataFrame:
    if not SNAPSHOT.exists():
        sys.exit(
            f"Portfolio snapshot not found: {SNAPSHOT}\n"
            "Run call_api.py first to generate it."
        )
    df = pd.read_csv(SNAPSHOT)
    df["rub_value"]  = pd.to_numeric(df["rub_value"],  errors="coerce").fillna(0)
    df["weight_pct"] = pd.to_numeric(df["weight_pct"], errors="coerce").fillna(0)
    return df


def plot(df: pd.DataFrame) -> None:
    _dark_theme()

    # ── Aggregations ──────────────────────────────────────────────────────────
    total = df["rub_value"].sum()

    by_type = (
        df.groupby("instrument_type")["rub_value"]
        .sum()
        .sort_values(ascending=False)
    )

    # Top-15 by value, excluding pure cash
    top15 = (
        df[df["instrument_type"] != "currency"]
        .groupby(["ticker", "instrument_type"])["rub_value"]
        .sum()
        .reset_index()
        .sort_values("rub_value", ascending=False)
        .head(15)
    )

    by_account = df.pivot_table(
        index="account",
        columns="instrument_type",
        values="rub_value",
        aggfunc="sum",
        fill_value=0,
    )

    # ── Figure ────────────────────────────────────────────────────────────────
    fig = plt.figure(figsize=(22, 14), facecolor=_DARK_BG)
    fig.text(0.5, 0.97, "PORTFOLIO  STRUCTURE",
             ha="center", fontsize=20, fontweight="bold",
             color=_TEXT, family="monospace")
    updated = df["updated_at"].iloc[0] if "updated_at" in df.columns else ""
    fig.text(0.5, 0.935, f"NAV  ·  {total:,.0f} ₽   ·   {updated}",
             ha="center", fontsize=11, color=_DIM)

    gs = GridSpec(2, 2, figure=fig,
                  left=0.05, right=0.97, top=0.91, bottom=0.06,
                  wspace=0.35, hspace=0.50)

    ax_donut = fig.add_subplot(gs[0, 0])
    ax_bar   = fig.add_subplot(gs[0, 1])
    ax_acct  = fig.add_subplot(gs[1, :])

    # ── Panel 1: Donut — by asset type ───────────────────────────────────────
    labels  = [TYPE_LABELS.get(t, t) for t in by_type.index]
    sizes   = by_type.values.tolist()
    colours = [TYPE_PALETTE.get(t, "#484F58") for t in by_type.index]

    wedges, _, autotexts = ax_donut.pie(
        sizes, labels=None, colors=colours,
        autopct=lambda p: f"{p:.1f}%" if p > 3 else "",
        pctdistance=0.76,
        wedgeprops={"linewidth": 2.5, "edgecolor": _DARK_BG, "width": 0.50},
        startangle=90, counterclock=False,
    )
    for at in autotexts:
        at.set_fontsize(8.5)
        at.set_color(_TEXT)
        at.set_fontweight("bold")

    ax_donut.text(0,  0.10, "NAV",           ha="center", color=_DIM,  fontsize=9)
    ax_donut.text(0, -0.15, f"{total/1e6:.1f}M ₽",
                  ha="center", color=_TEXT, fontsize=12, fontweight="bold")

    patches = [
        mpatches.Patch(
            color=TYPE_PALETTE.get(t, "#484F58"),
            label=f"{TYPE_LABELS.get(t, t)}  {v/total*100:.1f}%",
        )
        for t, v in zip(by_type.index, by_type.values)
    ]
    ax_donut.legend(handles=patches, loc="lower center",
                    bbox_to_anchor=(0.5, -0.30), ncol=2,
                    fontsize=8, framealpha=0, handlelength=0.8,
                    handletextpad=0.5, labelspacing=0.35)
    ax_donut.set_title("По типу актива",
                       color=_TEXT, fontsize=11, fontweight="bold", pad=12)

    # ── Panel 2: H-bars — top-15 positions ───────────────────────────────────
    tickers_r = list(reversed(top15["ticker"].tolist()))
    values_r  = list(reversed(top15["rub_value"].tolist()))
    types_r   = list(reversed(top15["instrument_type"].tolist()))
    bar_cols  = [TYPE_PALETTE.get(t, "#484F58") for t in types_r]

    bars = ax_bar.barh(range(len(tickers_r)), values_r,
                       color=bar_cols, height=0.62, edgecolor="none")
    ax_bar.set_yticks(range(len(tickers_r)))
    ax_bar.set_yticklabels(tickers_r, fontsize=8.5, color=_TEXT)
    ax_bar.set_xlabel("Стоимость (RUB)", color=_DIM, fontsize=9)
    ax_bar.set_title("Топ-15 позиций (без денег)",
                     color=_TEXT, fontsize=11, fontweight="bold", pad=12)
    ax_bar.xaxis.set_major_formatter(
        mticker.FuncFormatter(
            lambda x, _: f"{x/1e6:.1f}M" if x >= 1e6 else f"{x/1e3:.0f}K"
        )
    )
    ax_bar.grid(axis="x", linestyle="--", alpha=0.25)
    ax_bar.spines[["top", "right"]].set_visible(False)

    max_v = max(values_r) if values_r else 1
    for bar, val in zip(bars, values_r):
        pct = val / total * 100
        ax_bar.text(
            val + max_v * 0.01,
            bar.get_y() + bar.get_height() / 2,
            f"{val/1e3:.0f}K  {pct:.1f}%",
            va="center", ha="left", fontsize=7.5, color=_DIM,
        )

    # ── Panel 3: Stacked bars — by account ───────────────────────────────────
    accounts   = by_account.index.tolist()
    all_types  = by_account.columns.tolist()
    x          = np.arange(len(accounts))
    bottoms    = np.zeros(len(accounts))

    for itype in all_types:
        vals  = by_account[itype].values
        color = TYPE_PALETTE.get(itype, "#484F58")
        label = TYPE_LABELS.get(itype, itype)
        ax_acct.bar(x, vals, 0.45, bottom=bottoms,
                    color=color, label=label, edgecolor="none")
        for xi, (v, b) in enumerate(zip(vals, bottoms)):
            if total > 0 and v / total > 0.02:
                ax_acct.text(
                    xi, b + v / 2, f"{v/1e3:.0f}K",
                    ha="center", va="center",
                    fontsize=7, color="white", fontweight="bold",
                )
        bottoms += vals

    ax_acct.set_xticks(x)
    ax_acct.set_xticklabels(accounts, fontsize=9, color=_TEXT)
    ax_acct.set_ylabel("Стоимость (RUB)", color=_DIM, fontsize=9)
    ax_acct.set_title("По счетам",
                      color=_TEXT, fontsize=11, fontweight="bold", pad=12)
    ax_acct.yaxis.set_major_formatter(
        mticker.FuncFormatter(
            lambda x, _: f"{x/1e6:.1f}M" if x >= 1e6 else f"{x/1e3:.0f}K"
        )
    )
    ax_acct.legend(loc="upper right", fontsize=8, framealpha=0.25,
                   ncol=min(len(all_types), 6))
    ax_acct.grid(axis="y", linestyle="--", alpha=0.25)
    ax_acct.spines[["top", "right"]].set_visible(False)

    fig.text(0.97, 0.01, "T-Invest Portfolio Analytics",
             ha="right", color=_DIM, fontsize=8, style="italic")

    RESULTS.mkdir(exist_ok=True)
    fig.savefig(OUT_PATH, dpi=180, bbox_inches="tight", facecolor=_DARK_BG)
    plt.close(fig)
    print(f"✓ Saved → {OUT_PATH}")


def main() -> None:
    df = load_snapshot()
    total = df["rub_value"].sum()
    print(f"Loaded {len(df)} positions  ·  NAV {total:,.0f} ₽")
    plot(df)


if __name__ == "__main__":
    main()
